# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Homeo_Doctor1',
    'version': '1.0',
    'category': 'Sales/Sales',
    'summary': 'Hospital Management Software',

    'depends': [
        'product','hr','account','purchase'],
    'data': [
        "views/patient_reg.xml",
        "views/menu.xml",
        "views/medicine_entry.xml",
        "views/patient.xml",
        "views/doctor_profile_views.xml",
        "views/doctor_lab_report_views.xml",
        "views/product_product_inherit.xml",
        "views/pharmacy.xml",
        "views/admitted_patient_details.xml",
        "views/ot_management.xml",
        "views/patient_insurance.xml",
        "views/patient_appointments.xml",
        "views/doctor_department.xml",
        # "views/hr_module_custom.xml",
        "report/patient_report.xml",
        "report/transfer_print.xml",
        "report/patient_registion_report.xml",
        "report/admitted_patient_report.xml",
        "report/consultation_report.xml",
        "views/patient.xml",
        "views/ct_scan.xml",
        "views/mri_scan.xml",
        "views/x_ray_scan.xml",
        "views/patient_appointments.xml",
        "views/audiology.xml",
        "views/templates.xml",
        "report/ct_invoice_template.xml",
        "report/ct_reports.xml",
        "report/mri_invoice_template.xml",
        "report/mri_reports.xml",
        "report/x_ray_invoice_template.xml",
        "report/x_ray_reports.xml",
        "report/audiology_invoice_template.xml",
        "report/audiology_reports.xml",
        "report/lab_report.xml",
        "report/lab_report.xml",
        "report/Lab_report_report.xml",
        "report/report_patient_card.xml",
        "report/report_action.xml",
        "report/patient_challan_report.xml",
        "report/intent_report.xml",
        "report/lab_result_report.xml",
        "report/general_billing_report.xml",
        "report/view_patient_registration_report_wizard.xml",
        "report/general_billing_wizard_report.xml",
        "report/lab_report.xml",
        "report/lab_billing_wizard_report.xml",
        "report/pharmacy_description_report.xml",
        "report/supplier_billing_report.xml",
        "report/admitted_patient_billing_wizard.xml",
        "report/appointment_challan.xml",
        "report/admission_challan_report.xml",
        "report/admission_discharge_challan.xml",
        "report/ip_part_challan.xml",
        "report/all_in_one_report.xml",
        "report/combined_report_template.xml",
        "report/pharmacy_report_template.xml",
        "views/custom_title.xml",
        "views/account_move_view.xml",
        "views/register_paymeny.xml",
        "views/intent.xml",
        "views/casualty.xml",
        "views/stock_entry_view.xml",
        "views/appontment_payment_wizard.xml",
        "views/master.xml",
        "views/purchase_order_views.xml",
        "views/op_category.xml",
        "views/lab_payment_wizard.xml",
        "views/lab_resultant_confi.xml",
        "views/general_department.xml",
        "views/general_dept_costing.xml",
        "views/general_billing.xml",
        "views/general_billing.xml",
        "views/lab_result_page.xml",
        "views/room_config.xml",
        "views/hospital_block.xml",
        "views/hospital_room_type.xml",
        "views/admitted_patient_history.xml",
        "views/sale_return_form.xml",
        "views/stock_transfer.xml",
        "views/bill_status_wizard_view.xml",
        "views/ip_return_medicine.xml",
        "views/hr_employee_kanban_inherit.xml",
        "views/ip_part_billing.xml",
        "views/hr_employee.xml",
        "views/pharmacy_prescription_report_wizard.xml",
        "views/res_partner_inherit.xml",
        "views/dashboard_model_kanban.xml",
        "data/ir_sequence_data.xml",

    ],
    'assets': {
        'web.assets_backend': [
            'homeo_doctor/static/src/js/custom_filter.js',
            'homeo_doctor/static/src/js/blank_value.js',
            'homeo_doctor/static/src/css/styles.css',
        ],
    },
    'demo': [

    ],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
